baseURL = 'https://dnjdsxor21.github.io/'
title = '누누타운'
author = 'Nu4nu'

languageCode = 'ko-KR'
DefaultContentLanguage = "ko"
ignoreLogs = ['warning-goldmark-raw-html']
# ------------------------------
theme = 'paper' # themes/paper/
enableEmoji = true
enableRobotsTXT = true

[pagination]
    pagerSize = 5

[params]
    # header social icons
    github = 'dnjdsxor21'
    rss = true

    # color
    color = 'linen' # 'linen', 'wheat', 'gray'
    
    # home page profile
    avatar = 'dnjdsxor21@gmail.com' # gravater email or image url
    name = 'Nunu'
    bio = 'Biomedical AI Developer'

    # misc
    math = true  # KaTex math types
    localKatex = false
    favicon = 'img/favicons/favicon.ico'
    appleTouchIcon = 'img/favicons/apple-touch-icon.png'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true  # raw HTML 렌더링
    

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[menu]
    [[menu.main]]                             # menu on the top
        identifier = "about"                  # content/about.md 
        name = "About"                        # Name displayed on the menu
        url = "/about/"                       # url
        weight = 1                            # order
    [[menu.main]]
        identifier = "categories"
        name = "categories"
        url = "/categories/"
        weight = 2
    [[menu.main]]
        identifier = "series"
        name = "series"
        url = "/series/"
        weight = 3
    [[menu.main]]
        identifier = "archives"
        name = "archives"
        url = "/archives/"
        weight = 4

[params.giscus]
  repo = 'dnjdsxor21/dnjdsxor21.github.io'                 # see https://giscus.app for more details
  repoId = 'R_kgDONgrX0Q'
  category = 'General'
  categoryId = 'DIC_kwDONgrX0c4CldTm'
  mapping = 'pathname'
  theme = 'preferred_color_scheme'
  lang = 'ko'

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

[services]
    [services.googleAnalytics]
        id = 'G-SW5RDFVP82'

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']